apiVersion: v1
kind: Service
metadata:
  name: teehr-frontend
  labels:
    app: teehr-frontend
spec:
  type: ClusterIP
  selector:
    app: teehr-frontend
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http