kind: Build
type: container
name: teehr-jupyter-driver-image-edge
description: Build TEEHR Jupyter Driver Image
spec:
  dockerfile: Dockerfile.jupyter-driver
  localId: jupyter-driver
  publishId: jupyter-driver:${var.devTeehrVersion}
  buildArgs:
      TEEHR_VERSION: ${var.devTeehrVersion}
environments:
  - local
  - remote
---
kind: Build
type: container
name: teehr-jupyter-driver-image-stable
description: Build TEEHR Jupyter Driver Image
spec:
  dockerfile: Dockerfile.jupyter-driver
  localId: jupyter-driver
  publishId: jupyter-driver:${var.stableTeehrVersion}
  buildArgs:
      TEEHR_VERSION: ${var.stableTeehrVersion}
environments:
  - remote
dependencies:
  - build.teehr-jupyter-driver-image-edge